### ISSUE TITLE
Replace dependency on itextpdf with openpdf

### ISSUE THREAD

**Issue by kurtparten** [hhandoko/play2-scala-pdf#19]
## Outcome Desired

Remove dependency on itextpdf, as its licensing requirements are restrictive. Replace with dependencies to openpdf.

https://github.com/LibrePDF/OpenPDF

<hr>
In <code>build.sbt</code>

```
libraryDependencies += "org.xhtmlrenderer" % "flying-saucer-pdf" % "9.1.6"
libraryDependencies += "org.xhtmlrenderer" % "flying-saucer-core" % "9.1.6"
libraryDependencies += "com.github.librepdf" % "openpdf" % "1.0.4"
```

## Definition of Done

- All tests pass
- PDF examples are generated as before
- itextpdf-*.jar is no longer required

<hr>

## How to Demo

Confirm all test cases complete successfully.

**Comment by hhandoko** [comment]
Thanks, I'll have a look at this early next week. If OK, will bump the major version (due to the core dependency change).

**Comment by hhandoko** [comment]
I've just updated and published the latest version of the library, however it is still on `itext`.

Flying Saucer do have an OpenPDF version of their library, so I'll spike on it on the coming days.

**Comment by andreasrosdal** [comment]
Any updates on this?

**Comment by hhandoko** [comment]
Hi @andreasrosdal , sorry this fell out of my radar.

I've created a branch for this task, please have a look: https://github.com/hhandoko/play2-scala-pdf/tree/feature/switch_to_openpdf

**Comment by andreasrosdal** [comment]
Looks good!

**Comment by hhandoko** [comment]
Published to Maven Central, it'll take up to 24 hours for the artifacts to be available.

Do note the updated module ID, it's now `play26-scala-pdf` (or `play25-scala-pdf` for Play 2.5) for a more accurate semantics.
