### ISSUE TITLE
Failure to build: Could not find a suitable constructor in com.hhandoko.play.pdf.PdfGenerator. 

### ISSUE THREAD

**Issue by nielsen-at-cgt** [hhandoko/play2-scala-pdf#22]
## Expected Behaviour

A simple project should build.

<hr>

## Actual Behaviour

    Could not find a suitable constructor in com.hhandoko.play.pdf.PdfGenerator. 

    Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument 
    constructor that is not private.
     at com.hhandoko.play.pdf.PdfGenerator.class(PdfGenerator.scala:53)

<hr>

## Steps to Reproduce

*build.sbt*

     name := "testpdf"
     version := "1.0" 
     lazy val `testpdf` = (project in file(".")).enablePlugins(PlayScala)
    resolvers += "scalaz-bintray" at "https://dl.bintray.com/scalaz/releases"
    resolvers += "Akka Snapshot Repository" at "http://repo.akka.io/snapshots/"
    scalaVersion := "2.12.2"
    libraryDependencies ++= Seq( jdbc , ehcache , ws , specs2 % Test , guice,
    "com.hhandoko" %% "play2-scala-pdf" % "3.0.0.P26"  )
    unmanagedResourceDirectories in Test <+=  baseDirectory ( _ /"target/web/public/test" )  

*HomeController.scala*
 
    package controllers

    import com.hhandoko.play.pdf.PdfGenerator
    import javax.inject._
    import play.api.mvc._

    /**
     * This controller creates an `Action` to handle HTTP requests to the
     * application's home page.
     */
    @Singleton
    class HomeController @Inject()(pdfGen:PdfGenerator,cc: ControllerComponents) extends 
    AbstractController(cc) {

      /**
      * Create an Action to render an HTML page with a welcome message.
      * The configuration in the `routes` file means that this method
      * will be called when the application receives a `GET` request with
      * a path of `/`.
      */
      def index = Action {
       pdfGen.ok(views.html.index("Your new application is ready."),"http://localhost:9000")
     }

     }

**Comment by hhandoko** [comment]
Have you provided an implementation for PdfGenerator? An example can be found below:

https://github.com/hhandoko/play2-scala-pdf/blob/master/examples/play26-example/app/com/hhandoko/ApplicationModule.scala#L48

**Comment by nielsen-at-cgt** [comment]
That was the problem.  Thanks!

**Comment by hhandoko** [comment]
That's a good point, I'll update the library with a default module and update the instructions.

With the artifact identifier, it was the old one before I took it into my own repo. I've raised an issue with Scaladex to fix the stale entry.
