### ISSUE TITLE
Scala 2.13 release

### ISSUE THREAD

**Issue by denisftw** [hhandoko/play2-scala-pdf#31]
Play 2.7.3 is compiled against Scala 2.13, and `scalatestplus-play` is also available for 2.13, so I think it should be possible to release `play2-scala-pdf` as well.

Thanks!

**Comment by hhandoko** [comment]
Will look into this, no worries!

**Comment by hhandoko** [comment]
Scala 2.13 support for Play 2.7 has just been published. It'll take up to 48 hours for the repos to sync.

**Comment by denisftw** [comment]
Thanks!

**Comment by hhandoko** [comment]
No worries!
